# -*- coding: utf-8 -*-
"""OSS_ML_Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_LS7_Pn6qYkXQ9nHZEHA4R77wLhvTxnc
"""

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

data = load_breast_cancer()

X = data.data
y = data.target

print("데이터셋: Breast Cancer")
print("데이터 개수:", len(X))
print("특성 개수:", len(X[0]))

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

print("학습 데이터 개수:", len(X_train))
print("테스트 데이터 개수:", len(X_test))

model = DecisionTreeClassifier(random_state=42)

model.fit(X_train, y_train)

pred = model.predict(X_test)

acc = accuracy_score(y_test, pred)

print("모델: Decision Tree")
print("정확도:", acc)